config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  
  resources :customers

  resources :accounts

  root "customers#index"
end

app/models/customer.rb
class Customer < TablelessApplicationRecord

  has_no_table :database => :pretend_success

  column :id, :integer
  column :username, :string
  column :customer_type, :string
  column :date_of_birth, :date
  column :gender, :string
  column :phone_number, :string
  column :created_at, :date
  column :updated_at, :date

  def self.create(params)
    payload = params.to_json
    response = ApiClient.post("#{model_api_url}", payload)
    self.new.build_model(response)
  end

  def update(params)
    payload = params.to_json
    response = ApiClient.patch("#{model_api_url}/#{self.id}", payload)
    build_model(response)
  end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  require 'customer_datatable'

  def index
    rescue_wrapper {
      respond_to do |format|
        format.html
        format.json do
          render json: CustomersDatatable.new(view_context, []) 
        end
      end
    }
  end

  def show
    rescue_wrapper {
      @customer = Customer.find(params[:id])
    }
  end

  def new
    rescue_wrapper {  
      @customer = Customer.new
    }
  end

  def create
    rescue_wrapper {
      customer = Customer.create(customer_params)
      redirect_to customer_path(customer)
    }
  end
  
  def edit
    rescue_wrapper {
      @customer = Customer.find(params[:id])
    }
  end

  def update
    rescue_wrapper {  
      @customer = Customer.find(params[:id])
      data = @customer.update(customer_params)

      if data[:status] == "SUCCESS"
        redirect_to customer_path(@customer)
      else
        @customer = data[:model_object]
        render :edit
      end
    }
  end

  private

  def customer_params
    params.require(:customer).permit(
      :customer_type, :username, :date_of_birth, :gender, :phone_number
    )
  end
end

app/views/customers/_form.html.erb
<div class="row">
  <div class="col-sm-12">
    <section class="card">
      <div class="card-body">
        <%= simple_form_for(@customer) do |f| %>
          <div class="form-row">
            <div class="col-md-3 mb-3">
              <div class="form-group">
                <%= f.input :customer_type,
                  required: true,
                  input_html: { autocomplete: "customer_type" }
                %>
              </div>
            </div>
            <div class="col-md-3 mb-3">
              <div class="form-group">
                <%= f.input :username,
                  required: true,
                  input_html: { autocomplete: "username" }
                %>
              </div>
            </div>
            <div class="col-md-3 mb-3">
              <div class="form-group">
                <%= f.input :date_of_birth,
                  required: true,
                  input_html: { autocomplete: "date_of_birth" }
                %>
              </div>
            </div>
            <div class="col-md-3 mb-3">
              <div class="form-group">
                <%= f.input :gender, required: true, input_html: { autocomplete: "gender"} %>
              </div>
            </div>
          </div>
          <div class="form-row">
            <div class="col-md-3 mb-3">
              <div class="form-group">
                <%= f.input :phone_number,
                  required: true,
                  input_html: { autocomplete: "phone_number" }, label: "phone_number"
                %>
              </div>
            </div>
          </div>
          
          <div class="form-actions pull-right">
            <%= link_to "Cancel", :back, class: "btn btn-default" %>
            <%= f.button :submit, (@customer.new_record? ? "Create" : "Update"), class: "btn btn-primary" %>
          </div>
        <% end %>
      </div>
    </section>
  </div>
</div>

app/views/customers/_show.html.erb
<div class="row">
  <div class="col-md-12">
    <section class="card">
      <div class="card-body bio-graph-info">
        <div class="row p-details">
          <div class="bio-row">
            <p><span class="bold">Customer ID </span>: <%= @customer.id %></p>
          </div>
          <div class="bio-row">
            <p><span class="bold">User Name </span>: <%= @customer.username %></p>
          </div>
          <div class="bio-row">
            <p><span class="bold">customer_type </span>: <%= @customer.customer_type %></p>
          </div>
          <div class="bio-row">
            <p>
              <span class="bold">
                Date of Birth 
              </span>: 
              <%= format_date(@customer.date_of_birth) %>
            </p>
          </div>
          <div class="bio-row">
            <p><span class="bold">gender </span>: <%= @customer.gender %></p>
          </div>
          <div class="bio-row">
            <p><span class="bold">phone_number </span>: <%= @customer.phone_number %></p>
          </div>
          <div class="bio-row">
            <p>
              <span class="bold">
                Created At
              </span>: 
              <%= format_date_time @customer.created_at %>
            </p>
          </div>
          <div class="bio-row">
            <p>
              <span class="bold">
                Updated At
              </span>: 
              <%= format_date_time @customer.updated_at %>
            </p>
          </div>
        </div>
      </div>
    </section>
  </div>
</div>

app/views/customers/edit.html.erb
<div class="row">
  <div class="col-lg-12">
    <nav aria-label="breadcrumb" class="breadcrumb-bottom">
      <ol class="breadcrumb">
        <li class="breadcrumb-item">
          <a href="/"><i class="fa fa-home"></i> Home</a>
        </li>
        <li class="breadcrumb-item active">
          Customer Edit
        </li>
      </ol>
    </nav>
  </div>
</div>
<%= render 'form' %>

app/views/customers/index.html.erb
<div class="row">
  <div class="col-lg-12">
    <div class="white-bg row">
      <div class="col-lg-10">
        <nav aria-label="breadcrumb" class="breadcrumb-bottom">
          <ol class="breadcrumb">
            <li class="breadcrumb-item">
              <a href="/"><i class="fa fa-home"></i> Home</a>
            </li>
            <li class="breadcrumb-item active" aria-current="page">
              Customers
            </li>
          </ol>
        </nav>
      </div>
      <div class="col-lg-2 p-2">
        <%= link_to "Create Customer", new_customer_path, class: "btn btn-success" %>
      </div>
    </div>
  </div>
</div>
<div class="row">
  <div class="col-sm-12">
    <section class="card">
      <div class="card-body">
        <div class="adv-table">
          <%= content_tag :table, role: :datatable, class: 'table table-bordered table-striped', id: 'dynamic-table', data: { url: customers_path(format: :json) },style: "width: 100%" do %>
            <thead>
              <tr>
                <th>ID</th>
                <th>Username</th>
                <th>Type</th>
                <th>DOB</th>
                <th>Gender</th>
                <th>Phone Number</th>
                <th>Actions</th>
              </tr>
            </thead>
            <tbody>
            </tbody>
          <% end %>
        </div>
      </div>
    </section>
  </div>
</div>
<script>
  $(document).ready(function () {
    var tbl = $('#dynamic-table').DataTable({
      ajax: { 
        'url': $(this).data('url')
      },
      serverSide: false,
      columnDefs: [
        {
          'targets': 6,
          'orderable': false,
          'searchable': false
        }
      ],
      order: [[ 0, 'desc' ]]
    });
  });
</script>

app/views/customers/new.html.erb
<h2>New Customer</h2>

<%= render 'form', customer: @customer %>

<%= link_to 'Back', customers_path %>

app/views/customers/show.html.erb
<div class="row">
  <div class="col-lg-12">
    <nav aria-label="breadcrumb" class="breadcrumb-bottom">
      <ol class="breadcrumb">
        <li class="breadcrumb-item">
          <a href="/"><i class="fa fa-home"></i> Home</a>
        </li>
        <li class="breadcrumb-item">
          <a href="/customers">Customers</a>
        </li>
        <li class="breadcrumb-item active" aria-current="page">
          Customer Detail
          <%= link_to edit_customer_path(@customer) do %>
            <i class="fa fa-edit">
            </i>
            Edit
          <% end %>  
        </li>
      </ol>
    </nav>
  </div>
</div>
<section class="card">
  <div class="card-body bio-graph-info">
    <div class="tab-pane fade active show contract-show" id="details" role="tabpanel" aria-labelledby="details-tab">
      <%= render 'show' %>
    </div>
  </div>
</section>